/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Scar
 */
public class VendorGUI extends javax.swing.JFrame {
    
    Driver myDriver;
    
    public void setDriver(Driver driver1)
    {
        myDriver = driver1;
    }

    /**
     * Creates new form VendorGUI
     */
    public VendorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemSearch = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuitemClear = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Scar\\Documents\\NOVA\\2013 Fall\\CSC 202\\Assignment 2 Restaurant Vendor\\background.jpg")); // NOI18N
        jLabel1.setText(" ");

        jMenu1.setText("Menu");

        menuitemSearch.setText("Search");
        menuitemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemSearchActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemSearch);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clear/Exit");
        jMenu2.setToolTipText("");

        menuitemClear.setText("Clear");
        jMenu2.add(menuitemClear);

        menuitemExit.setText("Exit");
        menuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExitActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
        // exits program
        System.exit(0);
    }//GEN-LAST:event_menuitemExitActionPerformed

    private void menuitemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemSearchActionPerformed
        // opnes SearchGUI 
        new SearchGUI(myDriver).setVisible(true);
    }//GEN-LAST:event_menuitemSearchActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuitemClear;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemSearch;
    // End of variables declaration//GEN-END:variables
}
